### PR TITLE
Feat fa v5

### PR DESCRIPTION
**Pull request by alexjab**
This is an MR to add support for FontAwesome v5.

### CODE REVIEW

**Comment by knystol** [comment]
Looks great, could we merge the new files? Thanks.

**Comment by alexjab** [comment]
@knystol Sure, then I'll publish it on npm and bower.

**Comment by alexjab** [comment]
npm is done, not sure about bower since it's been a long time since I used it.

What do you use @knystol ?

**Comment by knystol** [comment]
Excellent work!

Brgds,
Ken

**Pull request merged**
